# Build Stage
FROM ubuntu:20.04 as builder

## Install build dependencies.
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y cmake clang curl git
RUN curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN ${HOME}/.cargo/bin/rustup default nightly
RUN ${HOME}/.cargo/bin/cargo install -f cargo-fuzz

## Add source code to the build stage.
ADD . /beacon-fuzz
WORKDIR /beacon-fuzz

RUN cd bls-fuzz/fuzz && git submodule init && git submodule update && ${HOME}/.cargo/bin/cargo fuzz build

# Package Stage
FROM ubuntu:20.04

COPY --from=builder beacon-fuzz/bls-fuzz/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_blst_serde_g1 /
COPY --from=builder beacon-fuzz/bls-fuzz/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_blst_serde_g2 /
COPY --from=builder beacon-fuzz/bls-fuzz/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_differential_add_g1 /
COPY --from=builder beacon-fuzz/bls-fuzz/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_differential_add_g2 /
COPY --from=builder beacon-fuzz/bls-fuzz/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_differential_mul_g1 /
COPY --from=builder beacon-fuzz/bls-fuzz/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_differential_mul_g2 /
COPY --from=builder beacon-fuzz/bls-fuzz/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_differential_serde_g1 /
COPY --from=builder beacon-fuzz/bls-fuzz/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_differential_serde_g2 /
COPY --from=builder beacon-fuzz/bls-fuzz/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_milagro_serde_g1 /
COPY --from=builder beacon-fuzz/bls-fuzz/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_milagro_serde_g2 /



